### ISSUE TITLE
Blood Casting does not work

### ISSUE THREAD

**Issue by TacocaTYT** [FallingColors/HexMod#700]
### Modloader

Fabric

### Minecraft version

1.20.1

### Hex Casting version

hexcasting-common-1.20.1-0.11.1-7-pre-645

### Modloader version

Laoder 0.15.11 API 0.92.2+1.20.1

### Modpack info

https://drive.proton.me/urls/8ZG3P79HQM#hYiLH5jwJceS

### Issue description

Overcasting/Bloodcasting does damage but does not perform the spell effects

things such as raycasts DO resolve properly and put the appropriate data on the stack but stuff like explosion fails to resolve

**Comment by object-Object** [comment]
Can you confirm that you're definitely using build 645? This was a known bug, but it should have been fixed in build 643.

**Comment by Robotgiggle** [comment]
Some context from discord: this is a separate bug from the armor one fixed in 643, but I wasn't able to reproduce it in a minimal pack with just hex+deps. It's likely a mod conflict, although figuring out what mod is causing the problem is probably still important.

**Comment by TacocaTYT** [comment]
> Can you confirm that you're definitely using build 645? This was a known bug, but it should have been fixed in build 643.

this modpack has had issues with bloodcasting from day 1, it was not fixed when we updated our hexcasting version the other day

**Comment by walksanatora** [comment]
confirmed. they (assuming they are `_katte` on discord) are using sam's branch with inline support
which was branched off *before* armor bloodcasting was fixed

**Comment by walksanatora** [comment]
upon checking `_katte`'s connections on discord @TacocaTYT is infact `_katte`. and has been provided with the proper tags to fix this in earlier versions

**Comment by object-Object** [comment]
okay so that's not build 645 then. please give the *actual* mod version in the future.
